/**
 * Reads YEC Task Manager.xlsx and outputs SQL migration for:
 *   users (auth + public), sections, task_types, tasks, task_members
 * Run: node scripts/export_old_tasks.cjs > supabase/migrations/20260508000007_import_old_tasks.sql
 */

const XLSX = require('xlsx')
const path = require('path')
const crypto = require('crypto')
const fs = require('fs')

const FILE = path.join(__dirname, '../old data/YEC Task Manager.xlsx')
const wb = XLSX.readFile(FILE)

// ── helpers ──────────────────────────────────────────────────────────────────

function sheet(name) {
  const key = Object.keys(wb.Sheets).find(k =>
    k.replace(/[^\w]/g, '') === name.replace(/[^\w]/g, '') || k.includes(name)
  )
  if (!key) throw new Error(`Sheet not found: ${name}`)
  return XLSX.utils.sheet_to_json(wb.Sheets[key], { defval: null })
}

function uuid5(ns, name) {
  const hash = crypto.createHash('sha1').update(ns + ':' + name).digest()
  hash[6] = (hash[6] & 0x0f) | 0x50
  hash[8] = (hash[8] & 0x3f) | 0x80
  const hex = hash.toString('hex').substring(0, 32)
  return [hex.slice(0,8), hex.slice(8,12), hex.slice(12,16), hex.slice(16,20), hex.slice(20,32)].join('-')
}

function esc(v) {
  if (v == null) return 'NULL'
  return "'" + String(v).replace(/'/g, "''") + "'"
}

function extractHex(v) {
  const m = String(v || '').match(/#([0-9A-Fa-f]{6})/)
  return m ? m[0] : '#94a3b8'
}

function serialToDate(v) {
  if (v == null || v === '') return null
  if (typeof v === 'number') {
    const d = XLSX.SSF.parse_date_code(Math.floor(v))
    if (!d || !d.y) return null
    return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`
  }
  const s = String(v).trim()
  if (!s) return null
  const m1 = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/)
  if (m1) return `${m1[3]}-${m1[2].padStart(2,'0')}-${m1[1].padStart(2,'0')}`
  const m2 = s.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (m2) return m2[0]
  return null
}

function serialToTime(v) {
  if (v == null || v === '') return null
  if (typeof v === 'number') {
    const totalSec = Math.round(v * 86400)
    const h = Math.floor(totalSec / 3600)
    const m = Math.floor((totalSec % 3600) / 60)
    return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:00`
  }
  const s = String(v).trim()
  const m = s.match(/^(\d{1,2}):(\d{2})/)
  if (m) return `${m[1].padStart(2,'0')}:${m[2]}:00`
  return null
}

function toBool(v) {
  if (v === true || String(v || '').toUpperCase() === 'TRUE') return 'TRUE'
  return 'FALSE'
}

function safeJson(v) {
  if (v == null || v === '') return "'[]'::jsonb"
  try {
    const parsed = typeof v === 'string' ? JSON.parse(v) : v
    return esc(JSON.stringify(parsed)) + '::jsonb'
  } catch {
    return "'[]'::jsonb"
  }
}

const out = []
const push = (...lines) => lines.forEach(l => out.push(l))

push('-- YEC Task Manager — Import old tasks (no calendar, no Drive)')
push('-- Generated by scripts/export_old_tasks.cjs')
push('BEGIN;')
push('')
push('-- Needed for password hashing')
push('CREATE EXTENSION IF NOT EXISTS pgcrypto;')
push('')
push('-- Clean up any partial data from previous failed migration runs')
push('DELETE FROM public.task_members;')
push('DELETE FROM public.tasks;')
push('DELETE FROM public.task_types;')
push('DELETE FROM public.sections;')
push('')

// ── 1. users (auth + public) ─────────────────────────────────────────────────
push('-- ── 1. users ──')
const usersRaw = sheet('Users')
const userIdMap = {}
const userEmailMap = {}   // oldId → email (for owner_id subquery in tasks)
const userMemberCodeMap = {} // user oldId (U001) → member code (M001) for task_members resolution

for (const r of usersRaw) {
  const oldId = String(r['id'] || '').trim()
  if (!oldId) continue
  const email = String(r['email'] || '').trim().toLowerCase()
  if (!email) continue
  const name = String(r['name'] || email).trim()
  const role = String(r['role'] || 'member').trim()
  const active = toBool(r['active'])
  const password = String(r['password'] || 'changeme').trim()
  const memberOld = String(r['member_id'] || '').trim()

  const newId = uuid5('user', oldId)
  userIdMap[oldId] = newId
  userEmailMap[oldId] = email
  const memberRef = String(r['member_id'] || '').trim()
  if (memberRef) userMemberCodeMap[oldId] = memberRef.toUpperCase()

  const memberSql = memberOld
    ? `(SELECT id FROM public.members WHERE code=${esc(memberOld.toUpperCase())} LIMIT 1)`
    : 'NULL'
  // Use DO $$ block: insert into auth.users if not exists by email, else update password
  push(`DO $u$`)
  push(`DECLARE _id uuid;`)
  push(`BEGIN`)
  push(`  SELECT id INTO _id FROM auth.users WHERE email = ${esc(email)};`)
  push(`  IF _id IS NULL THEN`)
  push(`    INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, aud, "role", raw_app_meta_data, raw_user_meta_data, created_at, updated_at)`)
  push(`    VALUES ('${newId}'::uuid, '00000000-0000-0000-0000-000000000000'::uuid, ${esc(email)},`)
  push(`      crypt(${esc(password)}, gen_salt('bf')), now(), 'authenticated', 'authenticated',`)
  push(`      '{"provider":"email","providers":["email"]}'::jsonb, ${esc(JSON.stringify({ name }))}::jsonb, now(), now());`)
  push(`    _id := '${newId}'::uuid;`)
  push(`  ELSE`)
  push(`    UPDATE auth.users SET encrypted_password=crypt(${esc(password)}, gen_salt('bf')), updated_at=now() WHERE id=_id;`)
  push(`  END IF;`)
  push(`  INSERT INTO public.users (id, email, name, role, member_id, active)`)
  push(`  VALUES (_id, ${esc(email)}, ${esc(name)}, ${esc(role)}, ${memberSql}, ${active})`)
  push(`  ON CONFLICT (id) DO UPDATE SET role=EXCLUDED.role, name=EXCLUDED.name, member_id=EXCLUDED.member_id, active=EXCLUDED.active;`)
  push(`END $u$;`)
  push('')
}

// ── 2. sections ──────────────────────────────────────────────────────────────
push('-- ── 2. sections ──')
const sectionsRaw = sheet('Sections')
const sectionIdMap = {}

for (const r of sectionsRaw) {
  const oldId = String(r['id'] || '').trim()
  if (!oldId) continue
  const title = String(r['title'] || '').trim()
  if (!title) continue
  const newId = uuid5('section', oldId)
  sectionIdMap[oldId] = newId
  const sortOrder = Number(r['sort_order'] || 0) || 0
  const active = toBool(r['active'])
  const icon = r['icon'] != null ? esc(r['icon']) : 'NULL'
  const color = r['color'] != null ? esc(r['color']) : 'NULL'

  push(`INSERT INTO public.sections (id, code, title, color, icon, sort_order, active)`)
  push(`VALUES ('${newId}'::uuid, ${esc(oldId)}, ${esc(title)}, ${color}, ${icon}, ${sortOrder}, ${active});`)
}
push('')

// ── 3. task_types ─────────────────────────────────────────────────────────────
push('-- ── 3. task_types ──')
const typesRaw = sheet('Task_Types')
const typeIdMap = {}

for (const r of typesRaw) {
  const oldId = String(r['id'] || '').trim()
  if (!oldId) continue
  const label = String(r['label'] || r['name'] || '').trim()
  if (!label) continue
  const newId = uuid5('tasktype', oldId)
  typeIdMap[oldId] = newId
  const color = extractHex(r['color'])

  push(`INSERT INTO public.task_types (id, name, color)`)
  push(`VALUES ('${newId}'::uuid, ${esc(label)}, ${esc(color)});`)
}
push('')

// ── 4. tasks (two-pass: insert without parent, then update parent) ───────────
push('-- ── 4. tasks ──')
const tasksRaw = sheet('Tasks')

// Build full taskIdMap first so parent lookups work regardless of row order
const taskIdMap = {}
for (const r of tasksRaw) {
  const oldId = String(r['id'] || '').trim()
  if (oldId) taskIdMap[oldId] = uuid5('task', oldId)
}

// Pass 1: insert all tasks (parent_task_id = NULL for now)
for (const r of tasksRaw) {
  const oldId = String(r['id'] || '').trim()
  if (!oldId) continue
  const title = String(r['title'] || '').trim()
  if (!title) continue

  const newId = taskIdMap[oldId]

  const sectionOld = String(r['section_id'] || '').trim()
  const sectionSql = sectionIdMap[sectionOld] ? `'${sectionIdMap[sectionOld]}'::uuid` : 'NULL'

  // task_type_id comes from first tag — old data has no task_type_id column
  const tagsStr = String(r['tags'] || '').trim()
  const tagsArr = tagsStr ? tagsStr.split(',').map(t => t.trim()).filter(Boolean) : []
  const firstTag = tagsArr[0] || ''
  const typeSql = typeIdMap[firstTag] ? `'${typeIdMap[firstTag]}'::uuid` : 'NULL'
  const tagsSql = tagsArr.length
    ? `ARRAY[${tagsArr.map(t => esc(t)).join(',')}]::text[]`
    : `ARRAY[]::text[]`

  // owner_id: look up by email since DO $u$ may have kept existing auth.users UUID
  const ownerOld = String(r['owner_id'] || '').trim()
  const ownerEmail = ownerOld.startsWith('U') ? userEmailMap[ownerOld] : null
  const ownerSql = ownerEmail
    ? `(SELECT id FROM public.users WHERE email=${esc(ownerEmail)} LIMIT 1)`
    : 'NULL'

  const startDate = serialToDate(r['start_date'])
  const endDate = serialToDate(r['end_date'])
  const startTime = serialToTime(r['start_time'])
  const endTime = serialToTime(r['end_time'])

  const description = r['description'] != null && r['description'] !== '' ? esc(r['description']) : 'NULL'
  const completed = toBool(r['completed'])
  const deleted = toBool(r['deleted'])
  const deletedDate = serialToDate(r['deleted_at'])
  const deletedAtSql = deletedDate ? `${esc(deletedDate)}::timestamptz` : 'NULL'
  const createdDate = serialToDate(r['created_at']) || '2026-01-01'
  const checklist = safeJson(r['checklist_json'])
  const attachments = safeJson(r['attachments_json'])

  push(`INSERT INTO public.tasks (id, code, section_id, title, description, start_date, end_date, start_time, end_time, task_type_id, owner_id, tags, checklist, attachments, completed, deleted, deleted_at, created_at)`)
  push(`VALUES (`)
  push(`  '${newId}'::uuid, ${esc(oldId)}, ${sectionSql}, ${esc(title)}, ${description},`)
  push(`  ${startDate ? esc(startDate) + '::date' : 'NULL'}, ${endDate ? esc(endDate) + '::date' : 'NULL'},`)
  push(`  ${startTime ? esc(startTime) + '::time' : 'NULL'}, ${endTime ? esc(endTime) + '::time' : 'NULL'},`)
  push(`  ${typeSql}, ${ownerSql},`)
  push(`  ${tagsSql}, ${checklist}, ${attachments},`)
  push(`  ${completed}, ${deleted}, ${deletedAtSql}, ${esc(createdDate)}::timestamptz`)
  push(`);`)
}
push('')

// Pass 2: set parent_task_id where applicable
push('-- task parent links')
for (const r of tasksRaw) {
  const oldId = String(r['id'] || '').trim()
  const parentOld = String(r['parent_task_id'] || '').trim()
  if (!oldId || !parentOld || !taskIdMap[oldId] || !taskIdMap[parentOld]) continue
  push(`UPDATE public.tasks SET parent_task_id='${taskIdMap[parentOld]}'::uuid WHERE id='${taskIdMap[oldId]}'::uuid;`)
}
push('')

// ── 5. task_members ───────────────────────────────────────────────────────────
push('-- ── 5. task_members ──')
const tmRaw = sheet('Task_Members')

for (const r of tmRaw) {
  const taskOld = String(r['task_id'] || '').trim()
  const memberOld = r['member_id'] != null ? String(r['member_id']).trim() : ''
  const committeeOld = r['committee_id'] != null ? String(r['committee_id']).trim() : ''

  if (!taskOld) continue
  const taskNew = taskIdMap[taskOld]
  if (!taskNew) continue

  const rowOldId = String(r['id'] || '').trim()
  const rowKey = rowOldId || (taskOld + ':' + (memberOld || committeeOld))
  const rowId = uuid5('tm', rowKey)

  if (memberOld) {
    // Resolve member code: if it's a U-code (user), map to member code via userMemberCodeMap
    const memberCode = memberOld.toUpperCase().startsWith('U')
      ? (userMemberCodeMap[memberOld.toUpperCase()] || null)
      : memberOld.toUpperCase()
    if (!memberCode) continue // no member to link
    // Use SELECT-based INSERT to skip if member not found (avoids CHECK constraint violation)
    push(`INSERT INTO public.task_members (id, task_id, member_id, role)`)
    push(`SELECT '${rowId}'::uuid, '${taskNew}'::uuid, m.id, 'assignee'`)
    push(`FROM public.members m WHERE m.code=${esc(memberCode)};`)
  } else if (committeeOld) {
    push(`INSERT INTO public.task_members (id, task_id, committee_id, role)`)
    push(`SELECT '${rowId}'::uuid, '${taskNew}'::uuid, c.id, 'assignee'`)
    push(`FROM public.committees c WHERE c.code=${esc(committeeOld)};`)
  }
}
push('')

push('COMMIT;')

const OUTPUT = path.join(__dirname, '../supabase/migrations/20260508000007_import_old_tasks.sql')
fs.writeFileSync(OUTPUT, out.join('\n'), { encoding: 'utf8' })
process.stderr.write(
  `Written: ${OUTPUT}\n` +
  `Done. Users: ${Object.keys(userIdMap).length}, Sections: ${Object.keys(sectionIdMap).length}, ` +
  `Types: ${Object.keys(typeIdMap).length}, Tasks: ${Object.keys(taskIdMap).length}\n`
)
